'use strict';
const symbols={
bag:'<rect x="5" y="6" width="14" height="15" rx="3"/><path d="M9 6V3h6v3M9 10v7m6-7v7M8 21v1m8-1v1"/>',
plane:'<path d="m3 14 7-3V4c0-2 4-2 4 0v7l7 3v3l-7-2v5l3 2H7l3-2v-5l-7 2Z"/>',
bus:'<rect x="5" y="3" width="14" height="16" rx="3"/><path d="M5 11h14M8 19v2m8-2v2M8 7h8M8 15h.01M16 15h.01"/>',
food:'<path d="M4 3v6a3 3 0 0 0 6 0V3M7 3v19M20 22V3c-4 2-5 8-5 11h5"/>',
hotel:'<path d="M3 21V8h18v13M3 17h18M7 8V3h10v5M7 12h2m6 0h2"/>',
pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
car:'<path d="m5 8 2-5h10l2 5M3 10a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v8H3v-8ZM6 18v3m12-3v3M6 12h2m8 0h2"/>',
walk:'<circle cx="13" cy="4" r="2"/><path d="m8 21 3-7m5 7-2-8-3-3 2-3 3 4 4 1M6 12l3-4 4-1"/>',
up:'<path d="M5 19h4v-4h4v-4h4V7h4M5 9V3h6M5 3l8 8"/>',
view:'<path d="m3 19 6-10 4 5 3-8 5 13H3Z"/><circle cx="6" cy="5" r="2"/>'
};
const icon=n=>'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(symbols[n]||symbols.pin)+'</svg>';
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const directions=(from,to,mode='transit',waypoints='')=>'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(from)+'&destination='+encodeURIComponent(to)+'&travelmode='+mode+(waypoints?'&waypoints='+encodeURIComponent(waypoints):'');
const ext=(label,url)=>'<a class="mini-link" href="'+escapeHTML(url)+'" target="_blank" rel="noopener noreferrer">'+label+' ↗</a>';
const hotel='菊南温泉ユウベルホテル';
const resort='フェニックス・シーガイア・オーシャン・タワー';
const sourceURLs={airport:'https://www.kumamoto-airport.co.jp/access/',terminal:'https://www.sankobus.jp/busportal/wp-content/uploads/noriba_kuma-bt.pdf',hotel:'https://kikunan-ublhotel.jp/qa/',bus:'https://www.kumamotodentetsu.co.jp/bus/select/cgi/table/program/kdroutep.cgi?bn=13&bs=28',nanpu:'https://www.miyakoh.co.jp/express/mediafile/nanpu_20260301.pdf',seagaia:'https://seagaia.co.jp/access/',imakin:'http://aso-imakin.com/menu/',sushi:'https://hero-umi.com/brands/ushibukamaru_sakuramachi/',kouran:'https://www.kourantei.com/',grass:'https://www.newkusasenri.com/'};
function overview(){return ''}
function stop(time,title,body,type='move',status='',id=''){return '<li'+(id?' id="'+id+'"':'')+' class="trip-stop '+type+'"><div class="stop-head"><span class="time">'+time+'</span><h3>'+icon(type==='meal'?'food':type==='sight'?'view':type==='stay'?'hotel':'bus')+' '+title+'</h3>'+(status?'<span class="tag">'+status+'</span>':'')+'</div>'+body+'</li>'}
const box=(body,cls='')=>'<div class="stop-card '+cls+'">'+body+'</div>';
const pad=body=>'<div class="card-pad">'+body+'</div>';
function leg(from,to,label,kind='bus',booked=false){return '<div class="ticket-label">'+icon(kind)+label+(booked?'<span class="tag">予約済み</span>':'')+'</div><div class="journey-leg"><div class="endpoint"><strong>'+from[0]+'</strong><b>'+from[1]+'</b></div><div class="leg-arrow">'+(from[2]||'')+'</div><div class="endpoint"><strong>'+to[0]+'</strong><b>'+to[1]+'</b></div></div>'}
function way(title,nodes,tone='',note=''){return '<div class="wayfinding '+tone+'"><div class="way-title">'+icon('pin')+title+'</div><div class="way-route">'+nodes.map((n,i)=>(i?'<span class="way-arrow" aria-hidden="true">→</span>':'')+'<div class="way-node '+(n.target?'target':'')+'">'+(n.number?'<strong>'+n.number+'</strong>':icon(n.icon||'walk'))+'<span>'+n.label+'</span>'+(n.small?'<small>'+n.small+'</small>':'')+'</div>').join('')+'</div>'+(note?'<p class="way-caption">'+note+'</p>':'')+'</div>'}
function terminalMap(target='17'){const blue=target==='17',color=blue?'#2465b0':'#be3349',dest=blue?'青ホーム':'赤ホーム';return '<div class="wayfinding '+(blue?'':'red')+'"><div class="way-title">'+icon('walk')+'桜町の乗り換えは、この順番</div><svg class="terminal-map" viewBox="0 0 320 174" role="img" aria-label="降車場所から2階コンコースに上がり、1階の'+dest+target+'番へ下ります"><rect x="18" y="13" width="284" height="48" rx="12" fill="white"/><text x="160" y="43" text-anchor="middle" fill="#172e34" font-size="15" font-weight="700">2F コンコースを歩く</text><path d="M65 117V74M65 79l-5 7m5-7 5 7M255 73v31m-5-5 5 5 5-5" stroke="'+color+'" stroke-width="2.5" fill="none" stroke-linecap="round"/><text x="83" y="99" font-size="13" fill="#526774">上がる</text><text x="192" y="93" font-size="13" fill="#526774">下りる</text><rect x="18" y="120" width="122" height="45" rx="10" fill="white"/><text x="79" y="148" text-anchor="middle" fill="#172e34" font-size="14">1F 降車場所</text><rect x="181" y="111" width="121" height="54" rx="10" fill="'+color+'"/><text x="195" y="131" fill="white" font-size="12">1F '+dest+'</text><text x="194" y="155" fill="white" font-size="23" font-weight="800">'+target+'番</text></svg><p class="way-caption">'+(blue?'青ホームへは2F経由。1Fの車道は横断しない。':'青ホーム側で降りた場合の順路。現地の赤い案内サインへ。')+'</p></div>'}
function refs(entries,notes=''){return '<details class="reference-box"><summary>予約メモ・公式情報</summary><div class="reference-content">'+notes+entries.map(e=>ext(e[0],e[1])).join('')+'</div></details>'}
function meal({name,area,image,credit,creditURL,items=[],budget='',note='',url,query,alternative=''}){return box((image?'<img class="meal-photo" src="assets/'+image+'.webp" alt="'+escapeHTML(name+'の公式掲載料理写真')+'" width="960" height="650" loading="lazy"><div class="photo-credit">写真：'+(creditURL?'<a href="'+creditURL+'" target="_blank" rel="noopener noreferrer">'+credit+'</a>':credit)+'</div>':'')+'<div class="meal-body"><div class="meal-topline"><h4>'+name+'</h4><small>候補</small></div><p class="meal-place">'+icon('pin')+' '+area+'</p><ul class="menu-lines">'+items.map(x=>'<li><span>'+x[0]+'</span><b>'+x[1]+'</b></li>').join('')+'</ul>'+(note?'<p class="booking-note">'+note+'</p>':'')+'<div class="meal-footer"><span class="budget">'+budget+'</span>'+ext('地図',map(query||name))+'</div>'+(alternative?'<details class="food-alternative"><summary>ほかの候補</summary>'+alternative+'</details>':'')+'<div class="inline-links">'+(url?ext('お店・メニュー',url):'')+'</div></div>','meal-card')}
const dayContent={};

function glimpses(tiles){return '<div class="food-picks" aria-label="この日の食事">'+tiles.map(t=>'<button class="food-pick" data-jump="'+t.id+'"><img src="assets/'+t.image+'.webp" alt="'+escapeHTML(t.label)+'" width="460" height="300"><span class="pick-meal">'+t.when+'</span><span class="pick-title">'+t.label+'</span><small>'+t.price+'</small></button>').join('')+'</div>'}
const meals={
sushi:{name:'天草 牛深丸',area:'桜町3-10 · SAKURA MACHI 3F',image:'ushibukamaru',credit:'牛深丸 公式',creditURL:sourceURLs.sushi,items:[['牛深丸5貫盛り','店頭で確認'],['旬の地魚の握り','単品で追加']],budget:'1人 ¥2,500〜4,000目安',note:'11:00〜22:00（入店21:00まで）。掲載価格は未確認のため、予算は目安。',url:sourceURLs.sushi,query:'天草 牛深丸 SAKURA MACHI店'},
kouran:{name:'紅蘭亭 下通本店',area:'安政町5-26 · 下通アーケード',image:'kourantei',credit:'紅蘭亭 公式',creditURL:sourceURLs.kouran,items:[['太平燕（タイピーエン）','¥1,080'],['スーパイコ（酢排骨）','¥1,680'],['エビのチリソース','¥1,980']],budget:'料理の注文例：1人 ¥1,920',note:'太平燕を1人1杯＋スーパイコを2人でシェア。料理計¥3,840／2人。飲み物は別。',url:'https://www.kourantei.com/pdf/dinner_alacarte.pdf',query:'紅蘭亭 下通本店',alternative:'<p>ホテルで食べるなら「菊泉」の菖蒲御膳 ¥4,100も候補。夜の提供と席はホテルに確認。</p>'+ext('菊泉のメニュー','https://kikunan-ublhotel.jp/restaurant/')},
imakin:{name:'いまきん食堂',area:'阿蘇市内牧290 · 内牧温泉',image:'imakin',credit:'いまきん食堂 公式',creditURL:sourceURLs.imakin,items:[['あか牛丼','¥2,200'],['あか牛ハンバーグ定食','¥1,980'],['あか牛ビフテキ定食','¥3,400']],budget:'まずは、あか牛丼 ¥2,200',note:'10:00開店・16:00受付終了。ビフテキは1日10食限定。',url:sourceURLs.imakin,query:'いまきん食堂 阿蘇市内牧290',alternative:'<p>混んでいたら、草千里食堂へ。あか牛丼 ¥3,600、あか牛ハンバーグ定食 ¥2,300（公式表示額）。11:00〜16:00／LO15:00。</p>'+ext('草千里食堂のメニュー','https://www.newkusasenri.com/info/data/1.pdf')},
suganoya:{name:'菅乃屋 新市街店',area:'新市街2-10 · コンフォートホテル1F',image:'suganoya-shinshigai',credit:'菅乃屋 新市街店 公式',creditURL:'https://service.suganoya.com/shinshigai/',items:[['馬刺し盛り五種','¥3,600'],['馬焼き盛り五種','¥2,800'],['あったか焼きからし蓮根','¥680']],budget:'1人 ¥4,000〜5,000目安',note:'3皿を2人でシェアすると料理計¥7,080。ご飯・飲み物を予算に合わせて追加。',url:'https://service.suganoya.com/shinshigai/',query:'菅乃屋 新市街店'}
};
dayContent[15]=()=>overview([['菊南温泉','hotel'],['桜町BT','bus','赤5番'],['宮崎駅','bus','東口'],['シーガイア','hotel']])+
'<ol class="trip-list">'+
stop('○ 07:50','ホテルを出発',box(way('坂を下りて、路線バスの停留所へ',[{icon:'hotel',label:'ユウベル'},{icon:'walk',label:'徒歩 約5分',small:'坂を下る'},{icon:'bus',label:'菊南温泉前',target:true}],'green','ホテル玄関前の停留所ではなく「菊南温泉前」へ。')+pad(ext('バス停までの徒歩ルート',directions(hotel,'菊南温泉前 バス停 熊本電鉄','walking')))))+
stop('○ 08:15','路線バスで桜町へ',box(pad(leg(['08:15','菊南温泉前'],['09:00','桜町BT'],'C3-3 · 熊本駅／蓮台寺入口行き')+'<p class="one-note">山室経由。片道 ¥510／人。</p>')))+
stop('○ 09:30','宮崎行きの乗り場へ',box('<div class="platform-tip"><div class="platform-sign"><small>1F 赤</small><strong>5</strong></div><div class="platform-copy"><b>宮崎行き・なんぷう号</b><small>10:00発 · この5番で待つ</small></div></div>'+terminalMap('5')))+
stop('10:00','宮崎駅へ',box(pad(leg(['10:00','桜町BT'],['13:35','宮崎駅'],'高速バス なんぷう号','bus',true)+'<p class="soft-note">乗車券は予約メールから表示。スクリーンショットは使えません。</p>')))+
stop('○ 14:00','ホテルの無料バス',box(way('宮崎駅では「東口」へ',[{icon:'bus',label:'高速バス降車'},{icon:'walk',label:'駅の通路'},{number:'東',label:'東口',target:true}],'','西口に出たら、駅の東西通路で東口へ。')+pad(leg(['14:00','宮崎駅 東口'],['14:30','シーガイア'],'ホテル無料送迎')+'<p class="one-note">予約不要・先着順。遅延・満席ならタクシーへ。</p>')))+
stop('午後','シーガイアに到着',box(pad('<h4 class="stay-name">フェニックス・シーガイア<br>オーシャン・タワー</h4><div class="info-row"><span>15・16日の2泊</span><span>朝夕食付き</span></div>'+ext('ホテルの場所',map(resort)))),'stay','予約済み')+
stop('19:30','鉄板焼き「ふかみ」',box(pad('<h4 class="stay-name">ホテルで鉄板焼きディナー</h4><p class="one-note">予約時間は19:30。追加 ¥20,000／2人。</p>')),'meal','予約済み')+
'</ol>'+refs([['08:15便の経路',sourceURLs.bus],['桜町の構内図',sourceURLs.terminal],['なんぷう号 時刻表',sourceURLs.nanpu],['東口の送迎案内',sourceURLs.seagaia]],'<p>朝の路線バス・送迎バスは乗り継ぎ案。道路状況で遅れる場合があります。路線バスは現金や対応クレジットカードのタッチ決済などを用意（Suicaのみは不可）。</p><p>ホテル玄関前からの平日桜町方面は10:06発のため、朝は坂下の「菊南温泉前」を使用。</p>');
dayContent[16]=()=>overview([['朝ごはん','food'],['リゾート','view','自由時間'],['アルコ','food','19:00']])+
'<ol class="trip-list">'+
stop('朝','ホテルの朝食',box(pad('<h4 class="stay-name">朝食付きプラン</h4><p class="one-note">会場・時間はホテルの案内で確認。</p>')),'meal')+
stop('昼間','シーガイアで過ごす',box('<img class="scene-photo" src="assets/miyazaki-coast.webp" alt="宮崎の海辺を描いた旅のイメージイラスト" width="1536" height="1024" loading="lazy"><div class="photo-credit">旅のイメージイラスト</div>'+pad('<h4 class="stay-name">温泉・カフェ・リゾート散歩</h4><p class="one-note">日中は予定を詰めず、ふたりのペースで。</p>'+ext('リゾートの案内','https://seagaia.co.jp/'))),'sight')+
stop('19:00','リストランテアルコ',box(pad('<h4 class="stay-name">ホテルでイタリアン</h4><p class="one-note">追加 ¥4,600／2人。</p>')),'meal','予約済み')+
'</ol>'+refs([['シーガイア公式','https://seagaia.co.jp/']],'<p>宿泊予約額 ¥70,680 ＋夕食追加 ¥24,600＝¥95,280／2人。別途税・追加利用分は現地精算。</p><p>帰りの空港行きタクシーは、今日のうちにフロントへ相談。</p>');
dayContent[17]=()=>overview([['シーガイア','hotel'],['宮崎空港','plane','14:10発'],['羽田','plane','15:55着']])+
'<ol class="trip-list">'+
stop('朝','朝食・荷造り',box(pad('<h4 class="stay-name">チェックアウト</h4><p class="one-note">時間はホテルで確認。追加料金などを精算。</p>')),'stay')+
stop('○ 12:00','宮崎空港へ',box(pad(leg(['12:00','シーガイア'],['12:30','宮崎空港'],'タクシー案','car')+'<p class="one-note">車で約25分。配車は未手配。</p>')+way('空港に着いたら',[{icon:'plane',label:'荷物を預ける'},{icon:'walk',label:'保安検査'},{icon:'plane',label:'搭乗口',target:true}])) )+
stop('14:10','羽田へ',box(pad(leg(['14:10','宮崎'],['15:55','羽田'],'ソラシドエア 060便','plane',true))))+
'</ol>'+refs([['空港への公式アクセス',sourceURLs.seagaia]],'<p>ホテル〜空港の直行バスは土日祝限定。17日（木）はタクシー案。飛行機の搭乗口・締切は当日の案内で確認。</p>');


const catalog=window.FOOD_CATALOG;
const slotNames={l13:'13日のお昼',d13:'13日の夜',l14:'14日のお昼',d14:'14日の夜'};
const defaults={l13:'ushibukamaru',d13:'kourantei',l14:'imakin',d14:'suganoya'};
const dates=[{n:13,week:'日',area:'熊本',title:'熊本の街と、温泉。'},{n:14,week:'月',area:'阿蘇',title:'草千里へ、ドライブ。'},{n:15,week:'火',area:'宮崎',title:'熊本から、宮崎へ。'},{n:16,week:'水',area:'宮崎',title:'海辺で、のんびり。'},{n:17,week:'木',area:'帰る日',title:'宮崎から、羽田へ。'}];
const areaNames={city:'熊本市内',aso:'阿蘇・草千里',miyazaki:'宮崎'};
let lastPlanDay=13;
let choices={},activeLeg=0,leafletMap=null,mapLayers=null,pickerSlot=null,returnFocus=null;
function eligible(id,slot){const f=catalog.find(x=>x.id===id);return !!(f&&slotNames[slot]&&f.area===(slot==='l14'?'aso':'city')&&(slot[0]==='l'?f.lunch:f.dinner)&&(slot!=='l13'||id!=='kikusen'))}
function readChoices(){
 choices={};let saved={};try{saved=JSON.parse(localStorage.getItem('kyushu-food-v1')||'{}')}catch(e){}
 const params=new URLSearchParams(location.search);const shared=params.get('plan')==='1';
 Object.keys(slotNames).forEach(s=>{const id=shared?params.get(s):saved[s];if(eligible(id,s))choices[s]=id});
}
function picked(slot){return catalog.find(x=>x.id===(choices[slot]||defaults[slot]))}
function syncChoices(){try{localStorage.setItem('kyushu-food-v1',JSON.stringify(choices))}catch(e){}const url=new URL(location.href);url.searchParams.set('plan','1');Object.keys(slotNames).forEach(s=>{if(choices[s])url.searchParams.set(s,choices[s]);else url.searchParams.delete(s)});history.replaceState(null,'',url)}
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3000)}
function setChoice(slot,id){if(!eligible(id,slot))throw Error('この食事枠では選べません');choices[slot]=id;syncChoices();render();toast(slotNames[slot]+'に追加しました');return {slot,name:picked(slot).name}}
function foodLinks(f){return '<div class="food-links">'+ext('Googleマップ',map(f.query))+ext(f.official.includes('instagram.com')?'公式SNS':'公式HP',f.official)+ext('メニュー',f.menu)+'</div>'}
function foodCard(f,slot=null){const ok=slot?eligible(f.id,slot):false;return '<article class="dish-card"><div class="dish-image"><img src="assets/'+f.image+'" alt="'+escapeHTML(f.short)+'の公式料理写真" width="800" height="534" loading="lazy"><span>'+escapeHTML(f.genre)+'</span></div><div class="dish-content"><p class="eyebrow">'+escapeHTML(f.place)+'</p><h3>'+escapeHTML(f.name)+'</h3><p class="dish-why">'+escapeHTML(f.why)+'</p><ul class="menu-lines">'+f.menus.map(m=>'<li><span>'+escapeHTML(m[0])+'</span><b>'+escapeHTML(m[1])+'</b></li>').join('')+'</ul><p class="price-note">'+escapeHTML(f.budget)+'</p>'+foodLinks(f)+'<details class="dish-details"><summary>営業時間・場所</summary><p>'+escapeHTML(f.hours)+'</p><p>'+escapeHTML(f.note)+'</p><button class="map-inline-btn" data-inline-map="'+f.id+'">'+icon('pin')+' このページで地図を見る</button><div class="inline-map-slot"></div><a class="source-credit" target="_blank" rel="noopener noreferrer" href="'+escapeHTML(f.creditURL||f.official)+'">写真：'+escapeHTML(f.credit)+'</a></details>'+(slot?'<button class="choose-food" data-pick="'+f.id+'" data-slot="'+slot+'" '+(!ok?'disabled':'')+'>'+(ok?(choices[slot]===f.id?'✓ この店を選択中':slotNames[slot]+'にする'):(f.area!==(slot==='l14'?'aso':'city')?'別エリアの候補':!f.dinner&&slot[0]==='d'?'昼営業の候補':'この時間帯は対象外'))+'</button>':'')+'</div></article>'}
function railHTML(items,slot=null){return '<div class="rail-tools"><span>横にスワイプして選ぶ <b class="rail-count">1 / '+items.length+'</b></span><div><button data-rail-step="-1" aria-label="前の候補">←</button><button data-rail-step="1" aria-label="次の候補">→</button></div></div><div class="food-rail" tabindex="0" aria-label="料理の候補">'+items.map(f=>foodCard(f,slot)).join('')+'</div>'}
function compactMeal(slot){const f=picked(slot);return '<article class="chosen-meal"><img src="assets/'+f.image+'" alt="'+escapeHTML(f.short)+'" width="240" height="240" loading="lazy"><div><span class="eyebrow">'+(choices[slot]?'選んだ候補':'おすすめ案')+'</span><h4>'+escapeHTML(f.name)+'</h4><p>'+escapeHTML(f.menus[0][0])+' <b>'+escapeHTML(f.menus[0][1])+'</b></p><button data-open-picker="'+slot+'">写真でほかの候補を選ぶ →</button></div></article>'+foodLinks(f)}
function mealStop(slot,time){return stop(time,slot[0]==='l'?'昼ごはん':'夜ごはん',box(compactMeal(slot)),'meal','','meal-'+slot)}
function point(id,label){const found=(window.LOCATIONS||{})[id];if(found)return {id,name:label||found.name,query:found.query||found.name,coords:found.coords};const f=catalog.find(x=>x.id===id);return f?{id,name:label||f.name,query:f.query,coords:f.coords}:{id,name:label||id,query:label||id}}
function getRoute(n){
 const a=picked('l13'),b=picked('d13'),c=picked('l14'),d=picked('d14');
 if(n===13)return b.id==='kikusen'?{points:[point('airportK','熊本空港'),point('hotelK','ホテル · 荷物預け'),point(a.id),point('sakura','桜町BT'),point('hotelK','ホテル · 夜ごはん')],modes:['タクシー案 · 約35分','タクシー案 · 市中心部まで約20〜25分','街歩き / 市内移動','バス · 桜町 青17番'],actions:['まず荷物を預ける','身軽に街へ','観光のあと、乗り場へ','ホテルに戻る']}:{points:[point('airportK','熊本空港'),point('hotelK','ホテル · 荷物預け'),point(a.id),point(b.id),point('sakura','桜町BT'),point('hotelK','ホテル · 夜に戻る')],modes:['タクシー案 · 約35分','タクシー案 · 市中心部まで約20〜25分','街歩き / 市内移動','徒歩 / 市内移動','バス · 桜町 青17番'],actions:['まず荷物を預ける','身軽に街へ','観光・夜ごはん','帰りのバス乗り場','ホテルに戻る']};
 if(n===14)return {points:[point('hotelK','菊南温泉'),point(c.id),point('grass','草千里ヶ浜'),point(d.id),...(d.id==='kikusen'?[]:[point('hotelK','ホテル')])],modes:['車 · 阿蘇へ',c.id==='kusasenri'?'食堂から徒歩で草原へ':'車 · 草千里へ',d.id==='kikusen'?'車 · ホテルへ':'車 · 熊本へ',...(d.id==='kikusen'?[]:['タクシー案 · ホテルへ'])]};
 if(n===15)return {points:[point('hotelK','菊南温泉'),point('sakura','桜町BT'),point('stationM','宮崎駅'),point('seagaia','シーガイア')],modes:['坂下の停留所から C3-3','なんぷう号 · 赤5番','無料送迎 · 駅東口']};
 if(n===16)return {points:[point('seagaia','シーガイア')],modes:[]};
 return {points:[point('seagaia','シーガイア'),point('airportM','宮崎空港')],modes:['タクシー · 約25分']};
}

function routeThumb(p){const f=catalog.find(x=>x.id===p.id);if(f)return '<img src="assets/'+f.image+'" alt="" width="64" height="64">';if(p.id==='hotelK')return '<img src="assets/hotel-kikunan.webp" alt="" width="64" height="64">';if(p.id==='grass')return '<img src="assets/kusasenri-real.webp" alt="" width="64" height="64">';return icon(p.id.includes('airport')?'plane':p.id==='seagaia'?'hotel':'bus')}
function stepLabel(r,i,n){return r.actions?.[i]||(n===15?['坂下から路線バス','赤5番から宮崎へ','駅の東口からホテルへ'][i]:n===14?['阿蘇でランチ','草千里を歩く','夕食へ','ホテルに戻る'][i]:n===17?'空港へ':'この日の行き先')}
function mapSection(n){const route=getRoute(n);activeLeg=Math.min(activeLeg,Math.max(0,route.points.length-2));return '<section class="live-route" aria-label="この日の地図と移動"><div class="route-heading"><h3>'+icon('pin')+' '+(n===13?'ホテルに寄って、身軽に観光':n===15?'3つの乗り物で、宮崎へ':'今日の移動')+'</h3><button data-fit-route>全体を見る</button></div><div id="active-move"></div><div id="trip-map" class="trip-map"><div class="map-wait">地図を読み込み中…</div></div>'+(route.points.length>1?'<div class="route-steps photo-steps" aria-label="移動の順番・区間を選択">'+route.modes.map((m,i)=>'<button data-route-leg="'+i+'" aria-pressed="'+(i===activeLeg)+'"><span class="step-photo">'+routeThumb(route.points[i+1])+'<i>'+String(i+1).padStart(2,'0')+'</i></span><span class="step-text"><small>'+escapeHTML(stepLabel(route,i,n))+'</small><b>'+escapeHTML(route.points[i+1].name)+'</b></span><span class="step-chevron" aria-hidden="true">›</span></button>').join('')+'</div>':'')+'<p class="map-caption">区間をタップで表示切替 · 点線は移動のつながり</p></section>'}
function activeMove(n){const r=getRoute(n),a=r.points[activeLeg],b=r.points[activeLeg+1],mode=r.modes[activeLeg]||'';document.getElementById('active-move').innerHTML=b?'<div class="active-move"><div><small>ここから</small><b>'+escapeHTML(a.name)+'</b></div><span aria-hidden="true">→</span><div><small>ここへ</small><b>'+escapeHTML(b.name)+'</b></div></div><p class="move-mode">'+icon(/車|タクシー/.test(mode)?'car':/徒歩|街歩き/.test(mode)?'walk':'bus')+escapeHTML(mode)+'</p>':'<div class="single-location">'+escapeHTML(a.name)+'で過ごす日</div>'}
function initMap(n){
 activeMove(n);const r=getRoute(n),points=r.points.filter(p=>p.coords);
 if(!window.L||!points.length){document.getElementById('trip-map').innerHTML='<iframe title="目的地の地図" src="https://maps.google.com/maps?q='+encodeURIComponent(r.points[activeLeg+1]?.query||r.points[0].query)+'&output=embed&hl=ja" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';return}
 document.getElementById('trip-map').innerHTML='';
 leafletMap=L.map('trip-map',{scrollWheelZoom:false,zoomControl:true,attributionControl:true}).setView(points[0].coords,12);
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(leafletMap);
 mapLayers=L.layerGroup().addTo(leafletMap);
 const seen=new Set();r.points.forEach((p,i)=>{if(!p.coords)return;const key=p.coords.join(',');if(seen.has(key))return;seen.add(key);const same=r.points.map((q,j)=>q.coords&&q.coords.join(',')===key?j+1:null).filter(Boolean);L.marker(p.coords,{icon:L.divIcon({className:'route-pin',html:'<span>'+same.join('·')+'</span>',iconSize:[34,34],iconAnchor:[17,17]})}).addTo(leafletMap).bindPopup('<b>'+escapeHTML(p.name)+'</b><br>'+ext('Googleマップ',map(p.query))).on('click',()=>selectLeg(Math.min(i,r.modes.length-1),false))});
 if(points.length>1)L.polyline(points.map(p=>p.coords),{color:'#7f8b93',weight:2.5,dashArray:'5 8'}).addTo(leafletMap);
 selectLeg(activeLeg,true);
}
function selectLeg(i,fit=true){const n=selectedDay(),r=getRoute(n);activeLeg=Math.max(0,Math.min(i,r.points.length-2));activeMove(n);document.querySelectorAll('[data-route-leg]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.routeLeg)===activeLeg)));if(!leafletMap)return;mapLayers.clearLayers();const coords=[r.points[activeLeg]?.coords,r.points[activeLeg+1]?.coords].filter(Boolean);if(coords.length>1)L.polyline(coords,{color:'#dc3b35',weight:4,dashArray:'7 7'}).addTo(mapLayers);if(fit){const use=coords.length?coords:r.points.filter(p=>p.coords).map(p=>p.coords);leafletMap.fitBounds(L.latLngBounds(use),{padding:[35,35],maxZoom:15,animate:false})}}
function cityBus(toHotelEarly=false){return stop(toHotelEarly?'○ 夕方':'○ 19:55','桜町から菊南温泉へ',box(pad(toHotelEarly?'<p class="one-note">夕食前にホテルへ。菊南温泉前に停まるC系統の便を選ぶ。</p>':leg(['19:55','桜町BT'],['20:19','菊南温泉前'],'C1-2 · 菊池プラザ行き'))+terminalMap('17')+way('降りたらホテルへ',[{icon:'bus',label:'菊南温泉前'},{icon:'walk',label:'坂を上る',small:'徒歩 約5分'},{icon:'hotel',label:'ユウベル',target:true}],'green')+pad('<p class="one-note">片道 ¥510 / 人 · 現金などを用意</p>')))}
function returnHotel13(time='夜'){return stop(time,'同じホテルに戻る',box(pad('<div class="stay-simple">'+icon('bag')+'<div><b>荷物を受け取って、チェックイン</b><span>13・14日は菊南温泉に連泊</span></div></div>'+ext('Googleマップ',map(hotel)))),'stay')}
dayContent[13]=()=>'<ol class="trip-list">'+
stop('10:40','熊本へ',box(pad(leg(['10:40','羽田'],['12:30','熊本'],'ソラシドエア 013便','plane',true))))+
stop('○ 13:00','まずホテルへ直行',box(pad(leg(['13:00','熊本空港'],['13:35','ユウベルホテル'],'タクシー案 · 約35分','car'))+way('荷物を持ったままホテルへ',[{icon:'plane',label:'到着・荷物受取'},{icon:'car',label:'タクシー'},{icon:'hotel',label:'ホテル',target:true}],'','タクシーは未手配。時刻は到着後の目安。')+'<details class="route-alternative"><summary>バスでホテルへ行く場合</summary><p>空港4番 → 桜町BTで乗り換え → 菊南温泉前 → 徒歩約5分。特別快速は空港3番。</p>'+terminalMap('17')+'<p>乗り継ぎにより到着が遅くなるため、昼食と観光は後ろへ調整。</p></details>'))+
stop('○ 13:35','フロントに荷物を預ける',box('<div class="luggage-card"><img src="assets/hotel-kikunan.webp" alt="菊南温泉ユウベルホテルのロビー" width="800" height="658" loading="lazy"><div class="luggage-copy"><span class="action-badge">'+icon('bag')+' 荷物を預ける</span><h4>菊南温泉<br>ユウベルホテル</h4><p>チェックイン前も預かりOK。<br>身軽になって街へ。</p></div></div><div class="luggage-footer"><span>客室のチェックインは15:00〜</span>'+ext('ホテル公式FAQ',sourceURLs.hotel)+'</div><p class="source-credit hotel-credit">写真：菊南温泉ユウベルホテル 公式</p>'),'stay','','luggage13')+
stop('○ 13:50','ホテルから街へ',box(pad('<div class="journey-leg"><div class="endpoint"><b>ホテル</b><small>荷物はフロントに</small></div><div class="leg-arrow">タクシー案</div><div class="endpoint"><b>'+escapeHTML(picked('l13').name)+'</b></div></div><p class="one-note">市中心部まで車で約20〜25分。行き先・渋滞で変わります。</p>')+'<details class="route-alternative"><summary>路線バスで街へ出るなら</summary>'+way('坂下の「菊南温泉前」から',[{icon:'hotel',label:'ホテル'},{icon:'walk',label:'坂を下る',small:'徒歩 約5分'},{icon:'bus',label:'桜町方面',target:true}],'','発車時刻は当日の停留所案内で確認。')+ext('菊南温泉前の時刻表','https://www.kumamotodentetsu.co.jp/bus/select/sp/busstop/238/')+'</details>'))+
mealStop('l13','○ 14:30')+
stop('午後','手ぶらで熊本さんぽ',box('<button class="visit-teaser" data-go-guide="city"><img src="assets/josaien.webp" alt="桜の馬場 城彩苑" width="300" height="160"><span>城彩苑・街歩き・お土産<b>熊本のおすすめを見る →</b></span></button>'),'sight')+
(picked('d13').id==='kikusen'?cityBus(true)+returnHotel13('夕方')+mealStop('d13','○ 18:00'):mealStop('d13','○ 18:00')+cityBus()+returnHotel13('○ 20:25'))+
'</ol>'+refs([['ホテルの荷物預かり',sourceURLs.hotel],['空港から約35分','https://kikunan-ublhotel.jp/access/'],['桜町の構内図',sourceURLs.terminal],['19:55便の経路','https://www.kumamotodentetsu.co.jp/bus/select/cgi/table/program/kdroutep.cgi?bn=791&bs=6']],'<p>○は提案時刻。到着日の往路はタクシー案、夜はバスでホテルに戻る案。車・食事は未予約。バスを使う場合は当日の便に合わせて時刻を調整。</p><p>荷物預かりはホテル公式FAQで確認済み。ホテルへ戻る予定時刻は、荷物を預ける際にフロントへ伝える。</p>');
dayContent[14]=()=>'<ol class="trip-list">'+stop('○ 08:00','車で阿蘇へ',box(pad('<div class="drive-card">'+icon('car')+'<b>菊南温泉 → '+escapeHTML(picked('l14').name)+'</b></div><p class="one-note">'+(picked('l14').id==='rakudayama'?'高森まで足を延ばすドライブ案。':picked('l14').id==='kusasenri'?'草千里へ直接向かい、散策の前後にランチ。':'内牧であか牛丼を食べてから、草千里へ。')+'</p>')))+mealStop('l14',picked('l14').id==='imakin'?'○ 10:00':'○ 11:30')+stop('○ 13:00','草千里ヶ浜',box('<img class="scene-photo" src="assets/kusasenri-real.webp" alt="阿蘇・草千里ヶ浜の草原と池" width="960" height="640" loading="lazy">'+pad('<div class="scene-copy"><b>草原と池、阿蘇の大きな景色。</b><span>散策 1〜2時間の案</span></div><div class="food-links">'+ext('Googleマップ',map('草千里ヶ浜'))+ext('公式案内','https://www.asocity-kanko.jp/spot/kusasenri/')+'</div><p class="source-credit">写真：阿蘇市観光協会</p>')),'sight')+stop('○ 14:30','景色を見ながらコーヒー',box(pad('<b>草千里珈琲焙煎所</b><p class="one-note">ニュー草千里1Fでひと休み。</p>'+ext('Googleマップ',map('草千里珈琲焙煎所')))),'sight')+stop('○ 15:30','熊本へ戻る',box(pad('<div class="drive-card">'+icon('car')+'<b>草千里 → '+escapeHTML(picked('d14').id==='kikusen'?'ホテル':picked('d14').name)+'</b></div><p class="one-note">夕食と車の返却に余裕を持って出発。</p>')))+mealStop('d14','○ 18:30')+(picked('d14').id==='kikusen'?'':stop('食後','ホテルへ',box(pad('<b>'+escapeHTML(picked('d14').name)+' → 菊南温泉</b><p class="one-note">車返却後はタクシーの案。</p>')),'stay'))+'</ol>'+refs([['草千里の営業案内','https://www.newkusasenri.com/info/?mode=dsp&no=44']],'<p>この日の時刻は案。食事・車は未予約。草千里は9/6公式案内で通常営業、火口周辺は規制中。食事を変えたときは、各店の営業時間を確認。</p>');
function selectedDay(){const m=location.hash.match(/day(1[3-7])/);return m?Number(m[1]):13}
function viewState(){const m=location.hash.match(/^#explore\/(city|aso|miyazaki)(?:\/(play|eat))?/);return m?{view:'explore',area:m[1],kind:m[2]||'play'}:{view:'plan'}}
function guideCard(g){return '<article class="guide-card"><img src="assets/'+g.image+'" alt="'+escapeHTML(g.name)+'の実景" width="800" height="534" loading="lazy"><div class="guide-body"><p class="eyebrow">'+escapeHTML(g.tag||areaNames[g.area])+'</p><h3>'+escapeHTML(g.name)+'</h3><p>'+escapeHTML(g.why)+'</p><div class="guide-facts"><span>'+escapeHTML(g.duration)+'</span><b>'+escapeHTML(g.price)+'</b></div><p class="guide-note">'+escapeHTML(g.note||'')+'</p><details class="guide-hours"><summary>営業時間</summary><p>'+escapeHTML(g.hours)+'</p></details><button class="map-inline-btn" data-guide-map="'+g.id+'">'+icon('pin')+' ページ内で地図を見る</button>'+ext('Googleマップ',map(g.query||g.name))+ext('公式HP',g.official)+'<div class="inline-map-slot"></div><p class="source-credit">'+ext(g.credit,g.creditURL||g.official)+'</p></div></article>'}
function exploreHTML(s){const guides=window.AREA_GUIDES||[];const pics={city:guides.find(g=>g.id==='josaien')?.image||'kourantei.webp',aso:'kusasenri-real.webp',miyazaki:guides.find(g=>g.area==='miyazaki')?.image||'miyazaki-coast.webp'};const foods=catalog.filter(f=>f.area===s.area);return '<div class="explore-heading"><span class="eyebrow">寄り道のアイデア</span><h2>エリアから探す</h2></div><div class="area-tabs" aria-label="エリア">'+Object.keys(areaNames).map(a=>'<button data-area="'+a+'" aria-pressed="'+(a===s.area)+'"><img src="assets/'+pics[a]+'" alt="" width="220" height="150"><span>'+areaNames[a]+'</span></button>').join('')+'</div><div class="explore-kind" aria-label="楽しみ方"><button data-kind="play" aria-pressed="'+(s.kind==='play')+'">'+icon('view')+' あそぶ</button><button data-kind="eat" aria-pressed="'+(s.kind==='eat')+'">'+icon('food')+' たべる</button></div>'+(s.kind==='play'?'<div class="guide-intro"><h3>'+areaNames[s.area]+'なら、ここ。</h3><p>気になる場所だけ、旅の合間に。</p></div><div class="guides-grid">'+guides.filter(g=>g.area===s.area).map(guideCard).join('')+'</div>':'<div class="guide-intro"><h3>'+areaNames[s.area]+'のおいしいもの</h3><p>'+(s.area==='miyazaki'?'ホテルの夕食は予約済み。街に出る日のランチ候補。':'写真・メニュー・場所で選ぶ。食事の変更は旅程の昼・夜から。')+'</p></div>'+railHTML(foods))+'<p class="guide-note">営業時間・価格は9/12確認。所要時間は散策の目安です。</p>'}
function render(){
 if(leafletMap){leafletMap.remove();leafletMap=null;mapLayers=null}
 const s=viewState(),n=selectedDay();if(s.view==='plan')lastPlanDay=n;document.body.dataset.view=s.view;
 document.querySelector('.date-nav').hidden=s.view==='explore';document.querySelector('.trip-cover').hidden=s.view==='explore';
 document.querySelectorAll('[data-main-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.mainView===s.view?'page':'false'));
 document.getElementById('date-tabs').innerHTML=dates.map(x=>'<button class="date-tab" role="tab" id="tab-'+x.n+'" aria-controls="day-panel" aria-selected="'+(x.n===n)+'" tabindex="'+(x.n===n?0:-1)+'" data-day="'+x.n+'"><strong>'+x.n+'<small>'+x.week+'</small></strong><span>'+x.area+'</span></button>').join('');
 if(s.view==='explore'){document.getElementById('journey').innerHTML=exploreHTML(s);bindRails();return}
 const d=dates.find(x=>x.n===n);let content=dayContent[n]();if(n>=15)content=content.replace(/^<div class="route-map">[\s\S]*?<\/div><\/div><\/div>/,'');
 document.getElementById('journey').innerHTML='<div id="day-panel" role="tabpanel" aria-labelledby="tab-'+n+'"><div class="day-heading"><h2>'+d.title+'</h2><span class="day-number">DAY 0'+(n-12)+'</span></div>'+mapSection(n)+'<div class="schedule-heading"><h3>この日の予定</h3><span>○ は予定時刻</span></div>'+content+'</div>'+(n<17?'<button class="next-day" data-day="'+(n+1)+'">翌日 '+(n+1)+'日へ →</button>':'');initMap(n);
}
function bindRails(){document.querySelectorAll('.food-rail').forEach(rail=>{rail.addEventListener('scroll',()=>{const width=rail.firstElementChild?.getBoundingClientRect().width+16;const index=Math.max(1,Math.min(rail.children.length,Math.round(rail.scrollLeft/width)+1));const count=rail.previousElementSibling.querySelector('.rail-count');if(count)count.textContent=index+' / '+rail.children.length},{passive:true});rail.addEventListener('keydown',e=>{if(e.target===rail&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();rail.scrollBy({left:(rail.firstElementChild.getBoundingClientRect().width+16)*(e.key==='ArrowRight'?1:-1),behavior:'smooth'})}})})}
function showPicker(slot){pickerSlot=slot;returnFocus=document.activeElement;const dialog=document.getElementById('food-dialog');const sorted=[...catalog.filter(f=>f.area!=='miyazaki')].sort((a,b)=>Number(eligible(b.id,slot))-Number(eligible(a.id,slot))||Number(b.id===picked(slot).id)-Number(a.id===picked(slot).id));dialog.innerHTML='<div class="picker-head"><div><span class="eyebrow">その日の気分で選ぼう</span><h2>'+slotNames[slot]+'</h2></div><button class="close-dialog" data-close-dialog aria-label="閉じる">×</button></div><div class="picker-content">'+railHTML(sorted,slot)+'<p class="guide-note">選択は食事の候補です。お店の予約は行われません。</p><button class="reset-choice" data-reset-slot="'+slot+'">おすすめ案に戻す</button></div>';dialog.showModal();document.body.classList.add('dialog-open');bindRails()}
function closePicker(){const d=document.getElementById('food-dialog');d.close();document.body.classList.remove('dialog-open');const b=document.querySelector('[data-open-picker="'+pickerSlot+'"]');(b||returnFocus)?.focus()}
function showInlineMap(button,query){const parent=button.closest('.dish-details,.guide-body');const slot=parent.querySelector('.inline-map-slot');if(slot.innerHTML){slot.innerHTML='';button.setAttribute('aria-expanded','false');return}slot.innerHTML='<iframe title="'+escapeHTML(query)+'の地図" src="https://maps.google.com/maps?q='+encodeURIComponent(query)+'&output=embed&hl=ja" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';button.setAttribute('aria-expanded','true')}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.day){activeLeg=0;location.hash='day'+d.day}
 else if(d.mainView){location.hash=d.mainView==='plan'?'day'+lastPlanDay:'explore/city/play'}
 else if(d.area){location.hash='explore/'+d.area+'/'+(viewState().kind||'play')}
 else if(d.kind){location.hash='explore/'+viewState().area+'/'+d.kind}
 else if(d.goGuide){location.hash='explore/'+d.goGuide+'/play'}
 else if(d.openPicker){showPicker(d.openPicker)}
 else if(d.pick){setChoice(d.slot,d.pick);closePicker()}
 else if('closeDialog'in d){closePicker()}
 else if(d.resetSlot){delete choices[d.resetSlot];syncChoices();render();closePicker();toast('おすすめ案に戻しました')}
 else if(d.railStep){const rail=b.closest('.rail-tools').nextElementSibling;rail.scrollBy({left:(rail.firstElementChild.getBoundingClientRect().width+16)*Number(d.railStep),behavior:'smooth'})}
 else if('routeLeg'in d){selectLeg(Number(d.routeLeg))}
 else if('fitRoute'in d&&leafletMap){const pts=getRoute(selectedDay()).points.filter(p=>p.coords).map(p=>p.coords);leafletMap.fitBounds(L.latLngBounds(pts),{padding:[30,30],maxZoom:15})}
 else if(d.inlineMap){showInlineMap(b,catalog.find(f=>f.id===d.inlineMap).query)}
 else if(d.guideMap){const g=window.AREA_GUIDES.find(g=>g.id===d.guideMap);showInlineMap(b,g.query||g.name)}
});
document.getElementById('food-dialog').addEventListener('cancel',()=>document.body.classList.remove('dialog-open'));
document.getElementById('food-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget)closePicker()});
document.getElementById('date-tabs').addEventListener('keydown',e=>{const b=e.target.closest('[data-day]');if(!b||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=Number(b.dataset.day);const next=e.key==='Home'?13:e.key==='End'?17:13+(n-13+(e.key==='ArrowRight'?1:4))%5;history.replaceState(null,'','#day'+next);activeLeg=0;render();document.getElementById('tab-'+next).focus()});
window.addEventListener('popstate',()=>{readChoices();render()});
window.addEventListener('hashchange',()=>{readChoices();render();window.scrollTo({top:0,behavior:'instant'})});
document.getElementById('share').addEventListener('click',async()=>{syncChoices();const u=new URL(location.href);u.hash='day13';u.searchParams.delete('v');try{if(navigator.share)await navigator.share({title:'ふたりの九州旅',url:u.href});else{await navigator.clipboard.writeText(u.href);toast('選んだ食事付きのURLをコピーしました')}}catch(e){if(e.name!=='AbortError')toast('アドレスバーのURLを共有してください')}});
readChoices();render();
if(document.modelContext?.registerTool){
 document.modelContext.registerTool({name:'get_trip_meals',description:'Return the four current meal candidates for September 13 and 14 with available alternatives.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:async()=>({content:[{type:'text',text:JSON.stringify({selections:Object.keys(slotNames).map(slot=>({slot,label:slotNames[slot],id:picked(slot).id,name:picked(slot).name,selected:!!choices[slot]})),candidates:catalog.map(f=>({id:f.id,name:f.name,slots:Object.keys(slotNames).filter(s=>eligible(f.id,s))}))})}]})});
 document.modelContext.registerTool({name:'choose_trip_meal',description:'Choose one restaurant candidate for a meal. Updates the visible itinerary and map. Does not book a restaurant.',inputSchema:{type:'object',properties:{slot:{type:'string',enum:Object.keys(slotNames)},restaurantId:{type:'string'}},required:['slot','restaurantId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async({slot,restaurantId})=>{try{return {content:[{type:'text',text:JSON.stringify(setChoice(slot,restaurantId))}]}}catch(e){return {isError:true,content:[{type:'text',text:e.message}]}}}});
}
