'use strict';
const symbols={
plane:'<path d="m3 14 7-3V4c0-2 4-2 4 0v7l7 3v3l-7-2v5l3 2H7l3-2v-5l-7 2Z"/>',
bus:'<rect x="5" y="3" width="14" height="16" rx="3"/><path d="M5 11h14M8 19v2m8-2v2M8 7h8M8 15h.01M16 15h.01"/>',
food:'<path d="M4 3v6a3 3 0 0 0 6 0V3M7 3v19M20 22V3c-4 2-5 8-5 11h5"/>',
hotel:'<path d="M3 21V8h18v13M3 17h18M7 8V3h10v5M7 12h2m6 0h2"/>',
pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
car:'<path d="m5 8 2-5h10l2 5M3 10a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v8H3v-8ZM6 18v3m12-3v3M6 12h2m8 0h2"/>',
walk:'<circle cx="13" cy="4" r="2"/><path d="m8 21 3-7m5 7-2-8-3-3 2-3 3 4 4 1M6 12l3-4 4-1"/>',
up:'<path d="M5 19h4v-4h4v-4h4V7h4M5 9V3h6M5 3l8 8"/>',
view:'<path d="m3 19 6-10 4 5 3-8 5 13H3Z"/><circle cx="6" cy="5" r="2"/>'
};
const icon=n=>'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(symbols[n]||symbols.pin)+'</svg>';
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const directions=(from,to,mode='transit',waypoints='')=>'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(from)+'&destination='+encodeURIComponent(to)+'&travelmode='+mode+(waypoints?'&waypoints='+encodeURIComponent(waypoints):'');
const ext=(label,url)=>'<a class="mini-link" href="'+escapeHTML(url)+'" target="_blank" rel="noopener noreferrer">'+label+' ↗</a>';
const hotel='菊南温泉ユウベルホテル';
const resort='フェニックス・シーガイア・オーシャン・タワー';
const sourceURLs={airport:'https://www.kumamoto-airport.co.jp/access/',terminal:'https://www.sankobus.jp/busportal/wp-content/uploads/noriba_kuma-bt.pdf',hotel:'https://kikunan-ublhotel.jp/qa/',bus:'https://www.kumamotodentetsu.co.jp/bus/select/cgi/table/program/kdroutep.cgi?bn=13&bs=28',nanpu:'https://www.miyakoh.co.jp/express/mediafile/nanpu_20260301.pdf',seagaia:'https://seagaia.co.jp/access/',imakin:'http://aso-imakin.com/menu/',sushi:'https://hero-umi.com/brands/ushibukamaru_sakuramachi/',kouran:'https://www.kourantei.com/',grass:'https://www.newkusasenri.com/'};
function overview(stops){return '<div class="route-map"><div class="map-label"><span>この日の移動</span><small>順路の略図</small></div><div class="map-track">'+stops.map(s=>'<div class="map-place"><span class="map-dot">'+icon(s[1])+'</span><b>'+s[0]+'</b><small>'+(s[2]||'')+'</small></div>').join('')+'</div></div>'}
function stop(time,title,body,type='move',status='',id=''){return '<li'+(id?' id="'+id+'"':'')+' class="trip-stop '+type+'"><div class="stop-head"><span class="time">'+time+'</span><h3>'+icon(type==='meal'?'food':type==='sight'?'view':type==='stay'?'hotel':'bus')+' '+title+'</h3>'+(status?'<span class="tag">'+status+'</span>':'')+'</div>'+body+'</li>'}
const box=(body,cls='')=>'<div class="stop-card '+cls+'">'+body+'</div>';
const pad=body=>'<div class="card-pad">'+body+'</div>';
function leg(from,to,label,kind='bus',booked=false){return '<div class="ticket-label">'+icon(kind)+label+(booked?'<span class="tag">予約済み</span>':'')+'</div><div class="journey-leg"><div class="endpoint"><strong>'+from[0]+'</strong><b>'+from[1]+'</b></div><div class="leg-arrow">'+(from[2]||'')+'</div><div class="endpoint"><strong>'+to[0]+'</strong><b>'+to[1]+'</b></div></div>'}
function way(title,nodes,tone='',note=''){return '<div class="wayfinding '+tone+'"><div class="way-title">'+icon('pin')+title+'</div><div class="way-route">'+nodes.map((n,i)=>(i?'<span class="way-arrow" aria-hidden="true">→</span>':'')+'<div class="way-node '+(n.target?'target':'')+'">'+(n.number?'<strong>'+n.number+'</strong>':icon(n.icon||'walk'))+'<span>'+n.label+'</span>'+(n.small?'<small>'+n.small+'</small>':'')+'</div>').join('')+'</div>'+(note?'<p class="way-caption">'+note+'</p>':'')+'</div>'}
function terminalMap(target='17'){const blue=target==='17',color=blue?'#2465b0':'#be3349',dest=blue?'青ホーム':'赤ホーム';return '<div class="wayfinding '+(blue?'':'red')+'"><div class="way-title">'+icon('walk')+'桜町の乗り換えは、この順番</div><svg class="terminal-map" viewBox="0 0 320 174" role="img" aria-label="降車場所から2階コンコースに上がり、1階の'+dest+target+'番へ下ります"><rect x="18" y="13" width="284" height="48" rx="12" fill="white"/><text x="160" y="43" text-anchor="middle" fill="#172e34" font-size="15" font-weight="700">2F コンコースを歩く</text><path d="M65 117V74M65 79l-5 7m5-7 5 7M255 73v31m-5-5 5 5 5-5" stroke="'+color+'" stroke-width="2.5" fill="none" stroke-linecap="round"/><rect x="18" y="120" width="122" height="45" rx="10" fill="white"/><text x="79" y="148" text-anchor="middle" fill="#172e34" font-size="14">1F 降車場所</text><rect x="181" y="111" width="121" height="54" rx="10" fill="'+color+'"/><text x="195" y="131" fill="white" font-size="12">1F '+dest+'</text><text x="194" y="155" fill="white" font-size="23" font-weight="800">'+target+'番</text></svg><p class="way-caption">'+(blue?'青ホームへは2F経由。1Fの車道は横断しない。':'青ホーム側で降りた場合の順路。現地の赤い案内サインへ。')+'</p></div>'}
function refs(entries,notes=''){return '<details class="reference-box"><summary>予約メモ・公式情報</summary><div class="reference-content">'+notes+entries.map(e=>ext(e[0],e[1])).join('')+'</div></details>'}
function meal({name,area,image,credit,creditURL,items=[],budget='',note='',url,query,alternative=''}){return box((image?'<img class="meal-photo" src="assets/'+image+'.webp" alt="'+escapeHTML(name+'の公式掲載料理写真')+'" width="960" height="650" loading="lazy"><div class="photo-credit">写真：'+(creditURL?'<a href="'+creditURL+'" target="_blank" rel="noopener noreferrer">'+credit+'</a>':credit)+'</div>':'')+'<div class="meal-body"><div class="meal-topline"><h4>'+name+'</h4><small>候補</small></div><p class="meal-place">'+icon('pin')+' '+area+'</p><ul class="menu-lines">'+items.map(x=>'<li><span>'+x[0]+'</span><b>'+x[1]+'</b></li>').join('')+'</ul>'+(note?'<p class="booking-note">'+note+'</p>':'')+'<div class="meal-footer"><span class="budget">'+budget+'</span>'+ext('地図',map(query||name))+'</div>'+(alternative?'<details class="food-alternative"><summary>ほかの候補</summary>'+alternative+'</details>':'')+'<div class="inline-links">'+(url?ext('お店・メニュー',url):'')+'</div></div>','meal-card')}
const dayContent={};

function glimpses(tiles){return '<div class="food-picks" aria-label="この日の食事">'+tiles.map(t=>'<button class="food-pick" data-jump="'+t.id+'"><img src="assets/'+t.image+'.webp" alt="'+escapeHTML(t.label)+'" width="460" height="300"><span class="pick-meal">'+t.when+'</span><span class="pick-title">'+t.label+'</span><small>'+t.price+'</small></button>').join('')+'</div>'}
const meals={
sushi:{name:'天草 牛深丸',area:'桜町3-10 · SAKURA MACHI 3F',image:'ushibukamaru',credit:'牛深丸 公式',creditURL:sourceURLs.sushi,items:[['牛深丸5貫盛り','店頭で確認'],['旬の地魚の握り','単品で追加']],budget:'1人 ¥2,500〜4,000目安',note:'11:00〜22:00（入店21:00まで）。掲載価格は未確認のため、予算は目安。',url:sourceURLs.sushi,query:'天草 牛深丸 SAKURA MACHI店'},
kouran:{name:'紅蘭亭 下通本店',area:'安政町5-26 · 下通アーケード',image:'kourantei',credit:'紅蘭亭 公式',creditURL:sourceURLs.kouran,items:[['太平燕（タイピーエン）','¥1,080'],['スーパイコ（酢排骨）','¥1,680'],['エビのチリソース','¥1,980']],budget:'料理の注文例：1人 ¥1,920',note:'太平燕を1人1杯＋スーパイコを2人でシェア。料理計¥3,840／2人。飲み物は別。',url:'https://www.kourantei.com/pdf/dinner_alacarte.pdf',query:'紅蘭亭 下通本店',alternative:'<p>ホテルで食べるなら「菊泉」の菖蒲御膳 ¥4,100も候補。夜の提供と席はホテルに確認。</p>'+ext('菊泉のメニュー','https://kikunan-ublhotel.jp/restaurant/')},
imakin:{name:'いまきん食堂',area:'阿蘇市内牧290 · 内牧温泉',image:'imakin',credit:'いまきん食堂 公式',creditURL:sourceURLs.imakin,items:[['あか牛丼','¥2,200'],['あか牛ハンバーグ定食','¥1,980'],['あか牛ビフテキ定食','¥3,400']],budget:'まずは、あか牛丼 ¥2,200',note:'10:00開店・16:00受付終了。ビフテキは1日10食限定。',url:sourceURLs.imakin,query:'いまきん食堂 阿蘇市内牧290',alternative:'<p>混んでいたら、草千里食堂へ。あか牛丼 ¥3,600、あか牛ハンバーグ定食 ¥2,300（公式表示額）。11:00〜16:00／LO15:00。</p>'+ext('草千里食堂のメニュー','https://www.newkusasenri.com/info/data/1.pdf')},
suganoya:{name:'菅乃屋 新市街店',area:'新市街2-10 · コンフォートホテル1F',image:'suganoya-shinshigai',credit:'菅乃屋 新市街店 公式',creditURL:'https://service.suganoya.com/shinshigai/',items:[['馬刺し盛り五種','¥3,600'],['馬焼き盛り五種','¥2,800'],['あったか焼きからし蓮根','¥680']],budget:'1人 ¥4,000〜5,000目安',note:'3皿を2人でシェアすると料理計¥7,080。ご飯・飲み物を予算に合わせて追加。',url:'https://service.suganoya.com/shinshigai/',query:'菅乃屋 新市街店'}
};
dayContent[13]=()=>overview([['熊本空港','plane'],['桜町・下通','food','昼・夜ごはん'],['菊南温泉','hotel']])+
glimpses([{id:'lunch13',image:'ushibukamaru',when:'昼',label:'天草の寿司',price:'¥2,500〜／人目安'},{id:'dinner13',image:'kourantei',when:'夜',label:'熊本名物・太平燕',price:'太平燕 ¥1,080'}])+
'<ol class="trip-list">'+
stop('10:40','羽田から熊本へ',box(pad(leg(['10:40','羽田'],['12:30','熊本'],'ソラシドエア 013便','plane',true))))+
stop('到着後','空港から市内へ',box(pad('<div class="journey-leg"><div class="endpoint"><b>熊本空港</b></div><div class="leg-arrow">空港リムジン</div><div class="endpoint"><b>桜町BT</b></div></div>')+way('空港の乗り場',[{icon:'plane',label:'1F 到着口'},{icon:'walk',label:'屋外へ'},{number:'4',label:'のりば',target:true}],'','桜町・熊本駅方面の通常便。特別快速は3番。')))+
stop('○ 14:30','お昼は寿司',meal(meals.sushi),'meal','','lunch13')+
stop('午後','下通をぶらり',box(pad('<div class="walk-strip">'+icon('walk')+'<b>桜町 → 下通アーケード</b></div><p class="one-note">お店を見ながら、夜ごはんの紅蘭亭へ。</p>'+ext('街歩きのルート',directions('SAKURA MACHI 熊本','紅蘭亭 下通本店','walking')))),'sight')+
stop('○ 18:00','夜は熊本の郷土中華',meal(meals.kouran),'meal','','dinner13')+
stop('○ 19:55','バスで菊南温泉へ',box(pad(leg(['19:55','桜町BT'],['20:19','菊南温泉前'],'C1-2 · 菊池プラザ行き')+'<p class="one-note">片道 ¥510／人。夕食後、桜町へ戻る。</p>')+terminalMap('17')+way('バスを降りたら',[{icon:'bus',label:'菊南温泉前'},{icon:'walk',label:'坂を上る',small:'徒歩 約5分'},{icon:'hotel',label:'ホテル',target:true}],'green')))+
stop('○ 20:25','ホテルに到着',box(pad('<h4 class="stay-name">菊南温泉ユウベルホテル</h4><div class="info-row"><span>13・14日は連泊</span><span>夕食なし</span></div><p class="one-note">到着が夜になる予定を、事前にホテルへ連絡。</p>'+ext('ホテルの場所',map(hotel)))),'stay')+
'</ol>'+refs([['空港の乗り場',sourceURLs.airport],['桜町の構内図',sourceURLs.terminal],['19:55便の経路','https://www.kumamotodentetsu.co.jp/bus/select/cgi/table/program/kdroutep.cgi?bn=791&bs=6'],['ホテルの道順',sourceURLs.hotel],['紅蘭亭 営業案内','https://www.kourantei.com/restaurants']],'<p>飛行機は予約確認済み。食事・市内移動の時刻は案です。紅蘭亭は11:00〜21:00（LO20:00）。夕食の席と当日営業は未確認。</p>');
dayContent[14]=()=>overview([['菊南温泉','hotel'],['内牧','food','あか牛丼'],['草千里','view','散策・カフェ'],['熊本市内','food','馬肉料理']])+
glimpses([{id:'lunch14',image:'imakin',when:'昼',label:'いまきんのあか牛丼',price:'¥2,200'},{id:'dinner14',image:'suganoya-shinshigai',when:'夜',label:'馬刺しと馬焼き',price:'¥4,000〜／人目安'}])+
'<ol class="trip-list">'+
stop('○ 08:00','車で阿蘇へ',box(pad('<div class="journey-leg"><div class="endpoint"><b>菊南温泉</b></div><div class="leg-arrow">カーシェア</div><div class="endpoint"><b>内牧温泉</b></div></div>'+ext('いまきんへナビ',directions(hotel,'いまきん食堂 阿蘇市内牧290','driving')))))+
stop('○ 10:00','あか牛丼を食べる',meal(meals.imakin),'meal','','lunch14')+
stop('○ 13:00','草千里ヶ浜',box('<img class="scene-photo" src="assets/kusasenri-real.webp" alt="草千里ヶ浜の草原と池の実景" width="960" height="640" loading="lazy"><div class="photo-credit">写真：<a href="https://www.asocity-kanko.jp/spot/kusasenri/" target="_blank" rel="noopener noreferrer">阿蘇市観光協会</a></div>'+pad('<h4 class="stay-name">草原を歩いて、写真を撮る。</h4><div class="info-row"><span>散策 1〜2時間ほど</span><span>駐車場 → 草原</span></div>'+ext('草千里駐車場へナビ',directions('いまきん食堂 阿蘇市内牧290','草千里駐車場','driving')))),'sight')+
stop('○ 14:30','草千里でコーヒー',box(pad('<h4 class="stay-name">草千里珈琲焙煎所</h4><p class="one-note">ニュー草千里1F。散策のあとにひと休み。</p>'+ext('施設の場所',map('草千里珈琲焙煎所')))),'sight')+
stop('○ 15:30','熊本へ戻る',box(pad('<div class="journey-leg"><div class="endpoint"><b>草千里</b></div><div class="leg-arrow">車</div><div class="endpoint"><b>熊本市内</b></div></div><p class="one-note">夕食の前に車を返却する案。</p>')))+
stop('○ 18:30','夜は馬肉料理',meal(meals.suganoya),'meal','','dinner14')+
stop('食後','菊南温泉に戻る',box(pad('<div class="journey-leg"><div class="endpoint"><b>新市街</b></div><div class="leg-arrow">タクシー案</div><div class="endpoint"><b>菊南温泉</b></div></div>'+ext('ホテルまでのルート',directions('菅乃屋 新市街店',hotel,'driving')))),'stay')+
'</ol>'+refs([['いまきんのメニュー',sourceURLs.imakin],['草千里の営業案内','https://www.newkusasenri.com/info/?mode=dsp&no=44'],['菅乃屋 店舗・メニュー',meals.suganoya.url]],'<p>この日の時刻はすべて案。草千里は9/6公式案内で営業中。火口周辺は規制があるため、草千里の散策を予定。</p><p>菅乃屋は17:00〜22:00（LO21:20）。席の事前確認がおすすめ。掲載料理の価格は1皿・税込、2人で分ける想定。</p>');
dayContent[15]=()=>overview([['菊南温泉','hotel'],['桜町BT','bus','赤5番'],['宮崎駅','bus','東口'],['シーガイア','hotel']])+
'<ol class="trip-list">'+
stop('○ 07:50','ホテルを出発',box(way('坂を下りて、路線バスの停留所へ',[{icon:'hotel',label:'ユウベル'},{icon:'walk',label:'徒歩 約5分',small:'坂を下る'},{icon:'bus',label:'菊南温泉前',target:true}],'green','ホテル玄関前の停留所ではなく「菊南温泉前」へ。')+pad(ext('バス停までの徒歩ルート',directions(hotel,'菊南温泉前 バス停 熊本電鉄','walking')))))+
stop('○ 08:15','路線バスで桜町へ',box(pad(leg(['08:15','菊南温泉前'],['09:00','桜町BT'],'C3-3 · 熊本駅／蓮台寺入口行き')+'<p class="one-note">山室経由。片道 ¥510／人。</p>')))+
stop('○ 09:30','宮崎行きの乗り場へ',box('<div class="platform-tip"><div class="platform-sign"><small>1F 赤</small><strong>5</strong></div><div class="platform-copy"><b>宮崎行き・なんぷう号</b><small>10:00発 · この5番で待つ</small></div></div>'+terminalMap('5')))+
stop('10:00','宮崎駅へ',box(pad(leg(['10:00','桜町BT'],['13:35','宮崎駅'],'高速バス なんぷう号','bus',true)+'<p class="soft-note">乗車券は予約メールから表示。スクリーンショットは使えません。</p>')))+
stop('○ 14:00','ホテルの無料バス',box(way('宮崎駅では「東口」へ',[{icon:'bus',label:'高速バス降車'},{icon:'walk',label:'駅の通路'},{number:'東',label:'東口',target:true}],'','西口に出たら、駅の東西通路で東口へ。')+pad(leg(['14:00','宮崎駅 東口'],['14:30','シーガイア'],'ホテル無料送迎')+'<p class="one-note">予約不要・先着順。遅延・満席ならタクシーへ。</p>')))+
stop('午後','シーガイアに到着',box(pad('<h4 class="stay-name">フェニックス・シーガイア<br>オーシャン・タワー</h4><div class="info-row"><span>15・16日の2泊</span><span>朝夕食付き</span></div>'+ext('ホテルの場所',map(resort)))),'stay','予約済み')+
stop('19:30','鉄板焼き「ふかみ」',box(pad('<h4 class="stay-name">ホテルで鉄板焼きディナー</h4><p class="one-note">予約時間は19:30。追加 ¥20,000／2人。</p>')),'meal','予約済み')+
'</ol>'+refs([['08:15便の経路',sourceURLs.bus],['桜町の構内図',sourceURLs.terminal],['なんぷう号 時刻表',sourceURLs.nanpu],['東口の送迎案内',sourceURLs.seagaia]],'<p>朝の路線バス・送迎バスは乗り継ぎ案。道路状況で遅れる場合があります。路線バスは現金や対応クレジットカードのタッチ決済などを用意（Suicaのみは不可）。</p><p>ホテル玄関前からの平日桜町方面は10:06発のため、朝は坂下の「菊南温泉前」を使用。</p>');
dayContent[16]=()=>overview([['朝ごはん','food'],['リゾート','view','自由時間'],['アルコ','food','19:00']])+
'<ol class="trip-list">'+
stop('朝','ホテルの朝食',box(pad('<h4 class="stay-name">朝食付きプラン</h4><p class="one-note">会場・時間はホテルの案内で確認。</p>')),'meal')+
stop('昼間','シーガイアで過ごす',box('<img class="scene-photo" src="assets/miyazaki-coast.webp" alt="宮崎の海辺を描いた旅のイメージイラスト" width="1536" height="1024" loading="lazy"><div class="photo-credit">旅のイメージイラスト</div>'+pad('<h4 class="stay-name">温泉・カフェ・リゾート散歩</h4><p class="one-note">日中は予定を詰めず、ふたりのペースで。</p>'+ext('リゾートの案内','https://seagaia.co.jp/'))),'sight')+
stop('19:00','リストランテアルコ',box(pad('<h4 class="stay-name">ホテルでイタリアン</h4><p class="one-note">追加 ¥4,600／2人。</p>')),'meal','予約済み')+
'</ol>'+refs([['シーガイア公式','https://seagaia.co.jp/']],'<p>宿泊予約額 ¥70,680 ＋夕食追加 ¥24,600＝¥95,280／2人。別途税・追加利用分は現地精算。</p><p>帰りの空港行きタクシーは、今日のうちにフロントへ相談。</p>');
dayContent[17]=()=>overview([['シーガイア','hotel'],['宮崎空港','plane','14:10発'],['羽田','plane','15:55着']])+
'<ol class="trip-list">'+
stop('朝','朝食・荷造り',box(pad('<h4 class="stay-name">チェックアウト</h4><p class="one-note">時間はホテルで確認。追加料金などを精算。</p>')),'stay')+
stop('○ 12:00','宮崎空港へ',box(pad(leg(['12:00','シーガイア'],['12:30','宮崎空港'],'タクシー案','car')+'<p class="one-note">車で約25分。配車は未手配。</p>')+way('空港に着いたら',[{icon:'plane',label:'荷物を預ける'},{icon:'walk',label:'保安検査'},{icon:'plane',label:'搭乗口',target:true}])) )+
stop('14:10','羽田へ',box(pad(leg(['14:10','宮崎'],['15:55','羽田'],'ソラシドエア 060便','plane',true))))+
'</ol>'+refs([['空港への公式アクセス',sourceURLs.seagaia]],'<p>ホテル〜空港の直行バスは土日祝限定。17日（木）はタクシー案。飛行機の搭乗口・締切は当日の案内で確認。</p>');

const dates=[{n:13,week:'日',area:'熊本',title:'熊本の街と、温泉。'},{n:14,week:'月',area:'阿蘇',title:'阿蘇・草千里へ。'},{n:15,week:'火',area:'宮崎',title:'熊本から、宮崎へ。'},{n:16,week:'水',area:'宮崎',title:'海辺で、のんびり。'},{n:17,week:'木',area:'帰る日',title:'宮崎から、羽田へ。'}];
function selectedDay(){const h=location.hash;const direct=h.match(/(?:day|itinerary)\/?(1[3-7])/);if(direct)return Number(direct[1]);if(/travel\/(morning|sakuramachi|seagaia)/.test(h))return 15;if(/travel\/airport-return/.test(h))return 17;if(/travel\/drive|food\/(imakin|kusasenri)/.test(h))return 14;if(h)return 13;const now=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Tokyo'});const n=Number(now.slice(-2));return now.startsWith('2026-09-')&&n>=13&&n<=17?n:13}
function render(){let n=selectedDay();if(!dayContent[n])n=13;const d=dates.find(x=>x.n===n);document.getElementById('date-tabs').innerHTML=dates.map(x=>'<button class="date-tab" id="tab-'+x.n+'" role="tab" aria-controls="day-panel" aria-selected="'+(x.n===n)+'" tabindex="'+(x.n===n?'0':'-1')+'" data-day="'+x.n+'" '+(!dayContent[x.n]?'disabled':'')+'><strong>'+x.n+'<small>'+x.week+'</small></strong><span>'+x.area+'</span></button>').join('');document.getElementById('journey').innerHTML='<div id="day-panel" role="tabpanel" aria-labelledby="tab-'+n+'"><div class="day-heading"><h2>'+d.title+'</h2><span class="day-number">DAY '+(n-12)+'</span></div>'+dayContent[n]()+'</div>'+(n<17&&dayContent[n+1]?'<button class="next-day" data-day="'+(n+1)+'">翌日 '+(n+1)+'日（'+dates[n-12].week+'）へ →</button>':'')}
function choose(n){if(!dayContent[n])return;location.hash='day'+n}
document.addEventListener('click',e=>{const jump=e.target.closest('[data-jump]');if(jump){document.getElementById(jump.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'});return;}const b=e.target.closest('[data-day]');if(b)choose(Number(b.dataset.day))});
document.getElementById('date-tabs').addEventListener('keydown',e=>{const b=e.target.closest('[data-day]');if(!b||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=Number(b.dataset.day);n=e.key==='Home'?13:e.key==='End'?17:13+(n-13+(e.key==='ArrowRight'?1:4))%5;if(dayContent[n]){history.replaceState(null,'','#day'+n);render();document.getElementById('tab-'+n).focus()}});
window.addEventListener('hashchange',()=>{render();document.getElementById('journey').scrollIntoView({behavior:'instant',block:'start'})});
document.getElementById('share').addEventListener('click',async()=>{const url=location.origin+location.pathname;try{if(navigator.share)await navigator.share({title:'ふたりの九州旅',url});else{await navigator.clipboard.writeText(url);const t=document.getElementById('toast');t.textContent='URLをコピーしました';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}}catch(e){if(e.name!=='AbortError'){const t=document.getElementById('toast');t.textContent='アドレスバーのURLを共有してください';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}}});
render();
